# Generated by Django 5.2.9 on 2026-04-23 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoParque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de Venta"
                    ),
                ),
                (
                    "existencia",
                    models.IntegerField(default=0, verbose_name="Stock/Existencia"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Producto del Parque",
                "verbose_name_plural": "Productos del Parque",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=150, verbose_name="Título del Evento"),
                ),
                (
                    "tipo_evento",
                    models.CharField(max_length=50, verbose_name="Tipo de Evento"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción General")),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADO", "Programado"),
                            ("EN_CURSO", "En Curso"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PROGRAMADO",
                        max_length=20,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField(verbose_name="Observación/Cambio")),
                (
                    "accion",
                    models.CharField(max_length=100, verbose_name="Acción Realizada"),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="parque.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
