# Generated by Django 5.2.9 on 2026-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="nombre_reserva",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nombre de la Reserva",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="zona",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Zona/Área"
            ),
        ),
    ]
