# Generated by Django 5.2.9 on 2026-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0002_evento_nombre_reserva_evento_zona"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="tipo_evento",
        ),
        migrations.AddField(
            model_name="evento",
            name="cant_combo_1",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Combos 10 (Brazaletes)"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="cant_combo_2",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Combos 5 (Brazaletes)"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="cant_individual",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Brazaletes Individuales"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="total_pagar",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Total a Pagar",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción General"
            ),
        ),
    ]
