# Generated by Django 5.2.9 on 2026-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0003_remove_evento_tipo_evento_evento_cant_combo_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoparque",
            name="sabor",
            field=models.CharField(
                choices=[("DULCE", "Dulce"), ("SALADO", "Salado"), ("NINGUNO", "N/A")],
                default="NINGUNO",
                max_length=10,
                verbose_name="Sabor",
            ),
        ),
        migrations.CreateModel(
            name="ComboParque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Combo"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="¿Qué incluye?"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio del Combo"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "productos",
                    models.ManyToManyField(
                        to="parque.productoparque", verbose_name="Productos incluidos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo del Parque",
                "verbose_name_plural": "Combos del Parque",
            },
        ),
    ]
