# Generated by Django 5.2.9 on 2026-04-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0004_productoparque_sabor_comboparque"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brazalete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre (ej: Combo #1)"
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Cantidad de Brazaletes que incluye"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio ($)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Brazalete",
                "verbose_name_plural": "Configuración de Brazaletes",
            },
        ),
    ]
