# Generated by Django 5.2.9 on 2026-04-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0005_brazalete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="cant_combo_1",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="cant_combo_2",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="cant_individual",
        ),
        migrations.AlterField(
            model_name="productoparque",
            name="sabor",
            field=models.CharField(
                choices=[
                    ("DULCE", "Dulce"),
                    ("SALADO", "Salado"),
                    ("BEBIDA", "Bebida"),
                    ("NINGUNO", "N/A"),
                ],
                default="NINGUNO",
                max_length=10,
                verbose_name="Sabor",
            ),
        ),
        migrations.CreateModel(
            name="DetalleEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_item",
                    models.CharField(
                        choices=[
                            ("BRAZALETE", "Brazalete"),
                            ("PRODUCTO", "Producto"),
                            ("COMBO", "Combo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                ("nombre_item", models.CharField(max_length=150)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="parque.evento",
                    ),
                ),
            ],
        ),
    ]
