# Generated by Django 5.2.9 on 2026-04-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0006_remove_evento_cant_combo_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comboparque",
            name="productos",
        ),
        migrations.RemoveField(
            model_name="productoparque",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="productoparque",
            name="existencia",
        ),
        migrations.CreateModel(
            name="ProductoEnCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="parque.comboparque",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parque.productoparque",
                    ),
                ),
            ],
        ),
    ]
