# Generated by Django 5.2.9 on 2026-04-24 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0007_remove_comboparque_productos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="responsable",
        ),
        migrations.AddField(
            model_name="evento",
            name="metodo_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIVISA", "Divisa"),
                    ("ZELLE", "Zelle"),
                    ("PAGO_MOVIL", "Pago móvil"),
                    ("PUNTO_VENTA", "Punto de venta"),
                    ("BIO_PAGO", "Bio pago"),
                    ("EFECTIVO_BS", "Efectivo Bolívares"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="fecha_inicio",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de Reserva"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="zona",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PULPO", "Pulpo"),
                    ("PARED_BLANCA", "Pared blanca"),
                    ("VENTANA", "Ventana"),
                ],
                max_length=100,
                null=True,
                verbose_name="Zona/Área",
            ),
        ),
    ]
