# Generated by Django 5.2.9 on 2026-04-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0008_remove_evento_responsable_evento_metodo_pago_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brazalete",
            name="precio",
        ),
        migrations.RemoveField(
            model_name="comboparque",
            name="precio",
        ),
        migrations.RemoveField(
            model_name="productoparque",
            name="precio",
        ),
    ]
