# Generated by Django 5.2.9 on 2026-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0009_remove_brazalete_precio_remove_comboparque_precio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="duracion_horas",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Duración (Horas)"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="hora_inicio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Inicio"
            ),
        ),
    ]
