# Generated by Django 5.2.9 on 2026-04-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0010_evento_duracion_horas_evento_hora_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="nota_forma_pago",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nota de Forma Pagos",
            ),
        ),
    ]
