# Generated by Django 5.2.9 on 2026-05-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0011_evento_nota_forma_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="fecha_abono1",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Abono 1"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha_abono2",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Abono 2"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="metodo_pago2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIVISA", "Divisa"),
                    ("ZELLE", "Zelle"),
                    ("PAGO_MOVIL", "Pago móvil"),
                    ("PUNTO_VENTA", "Punto de venta"),
                    ("BIO_PAGO", "Bio pago"),
                    ("EFECTIVO_BS", "Efectivo Bolívares"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de Pago (Abono 2)",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="monto_abono1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monto Abono 1",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="monto_abono2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monto Abono 2",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="nota_forma_pago2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nota de Forma Pagos (Abono 2)",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="metodo_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIVISA", "Divisa"),
                    ("ZELLE", "Zelle"),
                    ("PAGO_MOVIL", "Pago móvil"),
                    ("PUNTO_VENTA", "Punto de venta"),
                    ("BIO_PAGO", "Bio pago"),
                    ("EFECTIVO_BS", "Efectivo Bolívares"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de Pago (Abono 1)",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="nota_forma_pago",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nota de Forma Pagos (Abono 1)",
            ),
        ),
    ]
