# Generated by Django 5.2.9 on 2026-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0012_evento_fecha_abono1_evento_fecha_abono2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="banco",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Banco"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="confirmado",
            field=models.BooleanField(default=False, verbose_name="Confirmado"),
        ),
        migrations.AddField(
            model_name="evento",
            name="referencia_bancaria",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Referencia Bancaria",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="tasa_dia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Tasa del Día",
            ),
        ),
    ]
