# Generated by Django 5.2.9 on 2026-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0013_evento_banco_evento_confirmado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="confirmado",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Confirmado"
            ),
        ),
    ]
