# Generated by Django 5.2.9 on 2026-07-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0014_alter_evento_confirmado"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="banco2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Banco 2"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="confirmado2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Confirmado 2"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="referencia_bancaria2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Referencia Bancaria 2",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="tasa_dia2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Tasa del Día 2",
            ),
        ),
    ]
