# Generated by Django 5.2.9 on 2026-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parque", "0015_evento_banco2_evento_confirmado2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="foto_abono1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="parque/comprobantes/",
                verbose_name="Foto Comprobante Abono 1",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="foto_abono2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="parque/comprobantes/",
                verbose_name="Foto Comprobante Abono 2",
            ),
        ),
    ]
