# Generated by Django 5.2.9 on 2025-12-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(max_length=15)),
                ("cedula", models.CharField(max_length=20, unique=True)),
                ("direccion", models.TextField()),
            ],
        ),
    ]
