# Generated by Django 5.2.9 on 2025-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="11.222.333"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="juanito@gmail.com"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Juanito rojas"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=15, verbose_name="+58 412-3456789"),
        ),
    ]
