# Generated by Django 5.2.9 on 2025-12-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0002_alter_cliente_cedula_alter_cliente_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.CharField(max_length=20, unique=True, verbose_name="Cedula"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre y Apellido"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=15, verbose_name="Numero de telefono"),
        ),
    ]
