# Generated by Django 5.2.9 on 2025-12-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0003_alter_cliente_cedula_alter_cliente_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.IntegerField(
                max_length=20, unique=True, verbose_name="Cedula"
            ),
        ),
    ]
