# Generated by Django 5.2.9 on 2025-12-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0004_alter_cliente_cedula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Proveedor"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(max_length=15, verbose_name="Numero de telefono"),
                ),
                (
                    "razonsocial",
                    models.CharField(max_length=150, verbose_name="Razon Social"),
                ),
                (
                    "rif",
                    models.CharField(max_length=20, unique=True, verbose_name="RIF"),
                ),
                ("direccion", models.TextField()),
            ],
        ),
    ]
