# Generated by Django 5.2.9 on 2025-12-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0005_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_producto",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion del Producto"),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad en Stock")),
                (
                    "costo_actual",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo Actual"
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de Venta"
                    ),
                ),
                ("stock_minimo", models.IntegerField(verbose_name="Stock Minimo")),
                ("stock_maximo", models.IntegerField(verbose_name="Stock Maximo")),
            ],
        ),
    ]
