# Generated by Django 5.2.9 on 2025-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0006_inventario"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ELECTRONICA", "electrónica"),
                    ("ROPA", "Ropa"),
                    ("alimentación", "Alimentacion"),
                    ("HOGAR", "Hogar"),
                    ("OTRO", "Otro"),
                    ("BEBIDAS", "Bebidas"),
                ],
                default="OTRO",
                max_length=20,
                verbose_name="Categoria del Producto",
            ),
        ),
    ]
