# Generated by Django 5.2.9 on 2025-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0007_inventario_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.IntegerField(unique=True, verbose_name="Cedula"),
        ),
    ]
