# Generated by Django 5.2.9 on 2025-12-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0008_alter_cliente_cedula"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialProveedoresNotas",
            fields=[
                (
                    "id_historialproveedor",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                ("detalle_nota", models.TextField(verbose_name="Detalle de Nota")),
                (
                    "proveedores",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Proveedor",
                "verbose_name_plural": "Historial de Notas de Proveedores",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
