# Generated by Django 5.2.9 on 2025-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0009_historialproveedoresnotas"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="codigo_producto",
            field=models.CharField(
                blank=True,
                help_text="Código interno único (p. ej. SKU).",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Código del Producto",
            ),
        ),
    ]
