# Generated by Django 5.2.9 on 2025-12-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0010_inventario_codigo_producto"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientosInventario",
            fields=[
                ("id_movimiento", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        max_length=10,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "fecha_movimiento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Movimiento"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.inventario",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libreria.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
        ),
    ]
