# Generated by Django 5.2.9 on 2025-12-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0012_alter_inventario_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="dias_descuentos",
            field=models.CharField(
                blank=True,
                help_text="Ej: Lunes, Miércoles y Viernes",
                max_length=150,
                verbose_name="Días de Descuentos",
            ),
        ),
    ]
