# Generated by Django 5.2.9 on 2026-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0014_perfilusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="cedula",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="Cédula"
            ),
        ),
    ]
