# Generated by Django 5.2.9 on 2026-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0015_perfilusuario_cedula"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("almacenista", "Almacenista"),
                    ("vendedor", "Vendedor"),
                ],
                default="vendedor",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
