# Generated by Django 5.2.9 on 2026-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0016_perfilusuario_rol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="precio_venta",
        ),
        migrations.AddField(
            model_name="inventario",
            name="cantidad_por_empaque",
            field=models.IntegerField(default=1, verbose_name="Cantidad por Empaque"),
        ),
        migrations.AddField(
            model_name="inventario",
            name="costo_anterior",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Costo Anterior",
            ),
        ),
        migrations.AddField(
            model_name="inventario",
            name="unidad_empaque",
            field=models.CharField(
                choices=[
                    ("BULTO", "Bulto"),
                    ("CAJA", "Caja"),
                    ("PAQUETE", "Paquete"),
                    ("UNIDAD", "Unidad"),
                ],
                default="UNIDAD",
                max_length=20,
                verbose_name="Unidad del Empaque",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="cantidad",
            field=models.IntegerField(verbose_name="Cantidad Unitaria"),
        ),
    ]
