# Generated by Django 5.2.9 on 2026-01-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0017_remove_inventario_precio_venta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilusuario",
            name="foto",
        ),
    ]
