# Generated by Django 5.2.9 on 2026-01-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0018_remove_perfilusuario_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("inventario", "Inventario")],
                default="inventario",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
