# Generated by Django 5.2.9 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0019_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientosinventario",
            name="cantidad_empaques",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Cantidad de bultos, cajas o paquetes.",
                null=True,
                verbose_name="Cantidad de Empaques",
            ),
        ),
    ]
