# Generated by Django 5.2.9 on 2026-02-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0020_movimientosinventario_cantidad_empaques"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="unidad_empaque",
            field=models.CharField(
                choices=[
                    ("BULTO", "Bulto (20-50: Granos, Harina, Textiles)"),
                    ("CAJA", "Caja (6, 12, 24: Bebidas, Alimentos)"),
                    ("PAQUETE", "Paquete (10-12: Envoltorios menores)"),
                    ("UNIDAD", "Unidad (1: Detalle/Individual)"),
                ],
                default="UNIDAD",
                max_length=20,
                verbose_name="Unidad del Empaque",
            ),
        ),
    ]
