# Generated by Django 5.2.9 on 2026-02-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0021_alter_inventario_unidad_empaque"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientosinventario",
            name="unidad_empaque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNIDAD_1", "Unidad (1)"),
                    ("PAQUETE_10", "Paquete (10 unidades)"),
                    ("PAQUETE_12", "Paquete (12 unidades)"),
                    ("CAJA_6", "Caja (6 unidades)"),
                    ("CAJA_12", "Caja (12 unidades)"),
                    ("CAJA_24", "Caja (24 unidades)"),
                    ("BULTO_20", "Bulto (20 unidades)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Empaque",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="unidad_empaque",
            field=models.CharField(
                choices=[
                    ("UNIDAD_1", "Unidad (1)"),
                    ("PAQUETE_10", "Paquete (10 unidades)"),
                    ("PAQUETE_12", "Paquete (12 unidades)"),
                    ("CAJA_6", "Caja (6 unidades)"),
                    ("CAJA_12", "Caja (12 unidades)"),
                    ("CAJA_24", "Caja (24 unidades)"),
                    ("BULTO_20", "Bulto (20 unidades)"),
                ],
                default="UNIDAD_1",
                max_length=20,
                verbose_name="Unidad del Empaque",
            ),
        ),
    ]
