# Generated by Django 5.2.9 on 2026-02-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0022_movimientosinventario_unidad_empaque_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialproveedoresnotas",
            name="cantidad_empaques",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Cantidad de Empaques"
            ),
        ),
        migrations.AddField(
            model_name="historialproveedoresnotas",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="libreria.inventario",
                verbose_name="Producto (Opcional)",
            ),
        ),
        migrations.AddField(
            model_name="historialproveedoresnotas",
            name="total_unidades",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Total Unidades (Calc.)"
            ),
        ),
        migrations.AddField(
            model_name="historialproveedoresnotas",
            name="unidad_empaque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNIDAD_1", "Unidad (1)"),
                    ("PAQUETE_10", "Paquete (10 unidades)"),
                    ("PAQUETE_12", "Paquete (12 unidades)"),
                    ("CAJA_6", "Caja (6 unidades)"),
                    ("CAJA_12", "Caja (12 unidades)"),
                    ("CAJA_24", "Caja (24 unidades)"),
                    ("BULTO_20", "Bulto (20 unidades)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Empaque",
            ),
        ),
    ]
