# Generated by Django 5.2.9 on 2026-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0023_historialproveedoresnotas_cantidad_empaques_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historialproveedoresnotas",
            name="unidad_empaque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNIDAD", "Unidad"),
                    ("PAQUETE", "Paquete"),
                    ("CAJA", "Caja"),
                    ("BULTO", "Bulto"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Empaque",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="unidad_empaque",
            field=models.CharField(
                choices=[
                    ("UNIDAD", "Unidad"),
                    ("PAQUETE", "Paquete"),
                    ("CAJA", "Caja"),
                    ("BULTO", "Bulto"),
                ],
                default="UNIDAD",
                max_length=20,
                verbose_name="Unidad del Empaque",
            ),
        ),
        migrations.AlterField(
            model_name="movimientosinventario",
            name="unidad_empaque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNIDAD", "Unidad"),
                    ("PAQUETE", "Paquete"),
                    ("CAJA", "Caja"),
                    ("BULTO", "Bulto"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Empaque",
            ),
        ),
    ]
