# Generated by Django 5.2.9 on 2026-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0024_alter_historialproveedoresnotas_unidad_empaque_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("inventario", "Inventario"),
                    ("consulta", "Consulta"),
                ],
                default="inventario",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
