# Generated by Django 5.2.9 on 2026-02-21 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0025_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientosinventario",
            name="fecha_movimiento",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de Movimiento"
            ),
        ),
    ]
