# Generated by Django 5.2.9 on 2026-04-07 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0026_alter_movimientosinventario_fecha_movimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="libreria.proveedor",
                verbose_name="Proveedor",
            ),
        ),
    ]
