# Generated by Django 5.2.9 on 2026-04-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0027_inventario_proveedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="proveedor",
        ),
        migrations.AddField(
            model_name="inventario",
            name="proveedores",
            field=models.ManyToManyField(
                blank=True, to="libreria.proveedor", verbose_name="Proveedores"
            ),
        ),
    ]
