# Generated by Django 5.2.9 on 2026-04-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0028_remove_inventario_proveedor_inventario_proveedores"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientosinventario",
            name="codigo_lote",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código de Lote"
            ),
        ),
    ]
