# Generated by Django 5.2.9 on 2026-04-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0029_movimientosinventario_codigo_lote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="descripcion",
        ),
    ]
