# Generated by Django 5.2.9 on 2026-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0030_remove_inventario_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nombre del Proveedor",
            ),
        ),
    ]
