# Generated by Django 5.2.9 on 2026-04-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0032_migrate_nombre_to_razonsocial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientosinventario",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SALIDA", "Salida"),
                    ("PEDIDO", "Pedido (Info)"),
                ],
                max_length=10,
                verbose_name="Tipo de Movimiento",
            ),
        ),
    ]
