# Generated by Django 5.2.9 on 2026-04-16 01:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0033_alter_movimientosinventario_tipo_movimiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                ("id_pedido", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_pedido",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Pedido",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "codigo_lote",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código de Pedido"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Compra",
                "verbose_name_plural": "Pedidos de Comppras",
                "ordering": ["-fecha_pedido"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedidoCompra",
            fields=[
                ("id_detalle", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField(verbose_name="Cantidad Solicitada")),
                (
                    "unidad_empaque",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("PAQUETE", "Paquete"),
                            ("CAJA", "Caja"),
                            ("BULTO", "Bulto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Empaque",
                    ),
                ),
                (
                    "cantidad_empaques",
                    models.IntegerField(verbose_name="Cantidad de Empaques"),
                ),
                (
                    "cantidad_por_empaque",
                    models.IntegerField(default=1, verbose_name="Cantidad por Empaque"),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.inventario",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="libreria.pedidocompra",
                    ),
                ),
            ],
        ),
    ]
