# Generated by Django 5.2.9 on 2026-04-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0034_pedidocompra_detallepedidocompra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientosinventario",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                max_length=10,
                verbose_name="Tipo de Movimiento",
            ),
        ),
    ]
