# Generated by Django 5.2.9 on 2026-04-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0035_alter_movimientosinventario_tipo_movimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("inventario", "Inventario"),
                    ("consulta", "Consulta"),
                    ("soporte", "Soporte"),
                ],
                default="inventario",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
