# Generated by Django 5.2.9 on 2026-04-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0036_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("supervisor", "Supervisor"),
                    ("inventario", "Inventario"),
                    ("consulta", "Consulta"),
                    ("soporte", "Soporte"),
                    ("parque", "Parque"),
                ],
                default="inventario",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
