# Generated by Django 5.2.9 on 2026-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0037_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallepedidocompra",
            name="cantidad_empaques",
            field=models.FloatField(verbose_name="Cantidad de Empaques"),
        ),
        migrations.AlterField(
            model_name="historialproveedoresnotas",
            name="cantidad_empaques",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="Cantidad de Empaques"
            ),
        ),
        migrations.AlterField(
            model_name="movimientosinventario",
            name="cantidad_empaques",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Cantidad de bultos, cajas o paquetes.",
                null=True,
                verbose_name="Cantidad de Empaques",
            ),
        ),
    ]
