# Generated by Django 5.2.9 on 2026-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0038_alter_detallepedidocompra_cantidad_empaques_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="cantidad_vencido",
            field=models.IntegerField(default=0, verbose_name="Cantidad Vencida"),
        ),
        migrations.AlterField(
            model_name="movimientosinventario",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SALIDA", "Salida"),
                    ("TRASLADO_VENCIDO", "Traslado a Vencido"),
                ],
                max_length=20,
                verbose_name="Tipo de Movimiento",
            ),
        ),
    ]
