# Generated by Django 5.2.9 on 2026-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0039_inventario_cantidad_vencido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientosinventario",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SALIDA", "Salida"),
                    ("TRASLADO_VENCIDO", "Traslado a Vencido"),
                    ("CARGA_VENCIDO", "Carga Directa a Vencido"),
                ],
                max_length=20,
                verbose_name="Tipo de Movimiento",
            ),
        ),
    ]
