# Generated by Django 5.2.9 on 2026-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0040_alter_movimientosinventario_tipo_movimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="codigo_producto",
            field=models.CharField(
                default="0",
                help_text="Código interno único (p. ej. SKU).",
                max_length=20,
                unique=True,
                verbose_name="Código del Producto",
            ),
            preserve_default=False,
        ),
    ]
