# Generated by Django 5.2.9 on 2026-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0041_alter_inventario_codigo_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("supervisor", "Supervisor"),
                    ("inventario", "Inventario"),
                    ("consulta", "Consulta"),
                    ("soporte", "Soporte"),
                    ("parque", "Parque"),
                    ("almacenista", "Almacenista"),
                ],
                default="inventario",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
