# Generated by Django 5.2.9 on 2026-09-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0042_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientosinventario",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SALIDA", "Salida"),
                    ("TRASLADO_VENCIDO", "Traslado a Vencido"),
                    ("CARGA_VENCIDO", "Carga Directa a Vencido"),
                    ("SALIDA_VENCIDO", "Salida de Vencido"),
                ],
                max_length=20,
                verbose_name="Tipo de Movimiento",
            ),
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                ("id_lote", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codigo_lote",
                    models.CharField(max_length=50, verbose_name="Código de Lote"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de Vencimiento"),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.inventario",
                        verbose_name="Producto",
                    ),
                ),
            ],
        ),
    ]
