# Generated by Django 5.2.9 on 2026-09-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0043_alter_movimientosinventario_tipo_movimiento_lote"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="cantidad_actual",
            field=models.IntegerField(default=0, verbose_name="Cantidad Actual"),
        ),
    ]
