# Generated by Django 5.2.9 on 2026-09-23 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0044_lote_cantidad_actual"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="fecha_llegada",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de Llegada"
            ),
        ),
    ]
